{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudprober.fullname" . }}
data:
  cloudprober.{{- .Values.config.format }}: |
  {{- .Values.config | nindent 4}}
  {{ range .Values.additionalConfigs }}
  {{.name }}: |
  {{- .value | nindent 4}}
  {{- end }}
{{- end }}
