apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudprober.fullname" . }}
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudprober.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if $.Values.podAnnotations }}
          {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        checksum/config: {{ .Values.checksumOverride | default (include (print $.Template.BasePath "/configmap.yaml") . | sha256sum) }}
      labels:
        {{- if $.Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
        {{- include "cloudprober.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudprober.serviceAccountName" . }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cloudprober-config
          configMap:
            name: {{ include "cloudprober.config-map.name" . }}
        {{- range .Values.extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap | default .name }}
            defaultMode: {{ .defaultMode | default 400 }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- range .Values.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName | default .name }}
            defaultMode: {{ .defaultMode | default 400 }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
          {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config_file"
            - "/cfg/{{- .Values.configFileName -}}.{{- .Values.configFormat -}}"
            {{- if .Values.extraArgs }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: cloudprober-config
              mountPath: /cfg
            {{- range .Values.extraConfigmapMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
            {{- range .Values.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            # Assume that secrets are readOnly and we should not change that.
            {{- end }}
          ports:
            - name: http
              containerPort: 9313
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.extraContainers }}
        {{- . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
