{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudprober.fullname" . }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - apiGroups: ['']
    resources: ['*']
    verbs: ['get', 'list']
  - apiGroups:
      - extensions
      - 'networking.k8s.io' # k8s 1.14+
    resources:
      - ingresses
      - ingresses/status
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudprober.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloudprober.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudprober.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{end}}
