apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudprober.fullname" . }}
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default (printf "port-%v" .port) }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "cloudprober.selectorLabels" . | nindent 4 }}
