name: Publish Readme
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - '.github/workflows/publish_readme.yml'
  pull_request:
  workflow_dispatch:

jobs:
  publish_readme:
    name: Publish README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy README.md to gh-pages
        run: |-
          git worktree add repo gh-pages
          cd repo
          cp ../README.md .
          git diff

      - name: Push README changes
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        run: |-
          cd repo
          git add *
          git config user.name "Manu Garg"
          git config user.email "manugarg@gmail.com"
          git commit -m "[automated] Update helm charts repo" || exit 0
          git push
